import { Archetype } from "./questions";
import { InkCell } from "./scoring";
import {
  ARCHETYPE_RULES,
  ARCHETYPE_SKILLS,
  ARCHETYPE_MEMORIES,
  SkillTemplate,
  MemoryTemplate,
} from "./templates";
import { ARCHETYPES } from "./archetypes";

export interface GeneratedSeed {
  claudeMd: string;
  skills: { path: string; content: string }[];
  memories: { path: string; content: string }[];
}

export function generateSeed(cell: InkCell): GeneratedSeed {
  const claudeMd = generateClaudeMd(cell);
  const skills = generateSkills(cell);
  const memories = generateMemories(cell);
  return { claudeMd, skills, memories };
}

function generateClaudeMd(cell: InkCell): string {
  const pointInfo = ARCHETYPES[cell.point];
  const supportInfo = ARCHETYPES[cell.support];
  const specialistInfo = ARCHETYPES[cell.specialist];

  // Point gets all rules, support gets top 2, specialist gets top 1
  const pointRules = ARCHETYPE_RULES[cell.point];
  const supportRules = ARCHETYPE_RULES[cell.support].slice(0, 2);
  const specialistRules = ARCHETYPE_RULES[cell.specialist].slice(0, 1);

  const allRules = [...pointRules, ...supportRules, ...specialistRules];

  return `<!-- SEED:BEGIN - Generated by 13inks.dev -->
## AIO Recommendations
### Your Ink Cell
- **Point (${pointInfo.name}):** ${pointInfo.aiStyle}
- **Support (${supportInfo.name}):** ${supportInfo.aiStyle}
- **Specialist (${specialistInfo.name}):** ${specialistInfo.aiStyle}

### Rules
${allRules.map((r) => `- ${r}`).join("\n")}
<!-- SEED:END -->
`;
}

function generateSkills(cell: InkCell): { path: string; content: string }[] {
  const skills: { path: string; content: string }[] = [];

  // Point archetype gets its skill
  const pointSkills = ARCHETYPE_SKILLS[cell.point];
  for (const skill of pointSkills) {
    skills.push({
      path: `skills/${skill.name}/SKILL.md`,
      content: skill.content,
    });
  }

  // Support archetype gets its skill too
  const supportSkills = ARCHETYPE_SKILLS[cell.support];
  for (const skill of supportSkills) {
    skills.push({
      path: `skills/${skill.name}/SKILL.md`,
      content: skill.content,
    });
  }

  return skills;
}

function generateMemories(cell: InkCell): { path: string; content: string }[] {
  const memories: { path: string; content: string }[] = [];

  // Point archetype memory
  const pointMems = ARCHETYPE_MEMORIES[cell.point];
  for (const mem of pointMems) {
    memories.push({
      path: `memory/${mem.name}.md`,
      content: mem.content,
    });
  }

  // Support archetype memory
  const supportMems = ARCHETYPE_MEMORIES[cell.support];
  for (const mem of supportMems) {
    memories.push({
      path: `memory/${mem.name}.md`,
      content: mem.content,
    });
  }

  return memories;
}
